version: '3.7'


services:

  # db:
  #   image: bitnami/mysql:8.0
  #   volumes:
  #     - db_data:/bitnami/mysql
  #   environment:
  #     - MYSQL_USER=bn_wordpress
  #     - MYSQL_DATABASE=bitnami_wordpress
  #     - ALLOW_EMPTY_PASSWORD=yes

  db:
    image: bitnami/mariadb:10
    volumes:
      - db_data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_drupal
      - MARIADB_DATABASE=bitnami_drupal

  drupal:
    image: bitnami/drupal
    ports:
      - 8080:80
    volumes:
      - web_data:/bitnami
    depends_on:
      - db
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_NAME=bitnami_drupal


volumes:
  db_data:
    driver: local
  web_data:
    driver: local
