version: '3.7'


services:

  # https://hub.docker.com/_/mariadb
  # db
  #   image: bitnami/mysql:8.0
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db_data:/bitnami/mysql
  #   environment:
  #     - MYSQL_USER=bn_wordpress
  #     - MYSQL_DATABASE=bitnami_wordpress
  #     - ALLOW_EMPTY_PASSWORD=yes

  # # https://hub.docker.com/r/bitnami/mariadb
  # mariadb:
  #   image: bitnami/mariadb:10
  #   # command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db_data:/bitnami/mariadb
  #   environment:
  #     - MARIADB_DATABASE=nextcloud_db
  #     - MARIADB_USER=nextcloud
  #     - MARIADB_PASSWORD=password
  #     - MARIADB_ROOT_PASSWORD=password

  # https://hub.docker.com/r/mariadb
  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

  redis5:
  # https://hub.docker.com/_/redis/
  # https://hub.docker.com/r/bitnami/redis/
    image: bitnami/redis:5.0
    # container_name: redis5
    # restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password

  # https://github.com/nextcloud/docker
  nextcloud:
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - nextcloud-data:/var/www/html/data
      - nextcloud-config:/var/www/html/config
      - nextcloud-custom_apps:/var/www/html/custom_apps
      - nextcloud-apps:/var/www/html/apps
      - nextcloud-themes:/var/www/html/themes
    # depends_on:
    #   - mariadb
    environment:
      # REDIS
      - REDIS_HOST=redis5
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=password
      # MYSQL
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=maria10:3306

      - NEXTCLOUD_ADMIN_USER=admin
      # - NEXTCLOUD_DATA_DIR=/var/www/html
      - NEXTCLOUD_ADMIN_PASSWORD=password


volumes:
  db_data:
    driver: local
  nextcloud-data:
    driver: local
  nextcloud-config:
    driver: local
  nextcloud-custom_apps:
    driver: local
  nextcloud-apps:
    driver: local
  nextcloud-themes:
    driver: local
