version: '3.7'
services:
  # db:
  #   image: bitnami/mysql:8.0
  #   volumes:
  #     - mysql_data:/bitnami/mysql
  #   environment:
  #     - MYSQL_USER=bn_wordpress
  #     - MYSQL_DATABASE=bitnami_wordpress
  #     - ALLOW_EMPTY_PASSWORD=yes
  db:
    image: bitnami/mariadb:10
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: bitnami/wordpress:5
    ports:
      - 8080:8080
      # - 443:8443
    volumes:
      - wordpress_data:/bitnami/wordpress
    depends_on:
      - db
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  # mysql_data:
  #   driver: local
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local