version: '3.7'


services:

  # db:
  #   image: bitnami/mysql:8.0
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db_data:/bitnami/mysql
  #   environment:
  #     - MYSQL_USER=bn_wordpress
  #     - MYSQL_DATABASE=bitnami_wordpress
  #     - ALLOW_EMPTY_PASSWORD=yes

  db:
    image: bitnami/mariadb:10
    ports:
      - 3306:3306
    volumes:
      - db_data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_user
      - MARIADB_DATABASE=bitnami_db

  phabricator:
    image: bitnami/phabricator
    ports:
      - 8080:80
    volumes:
      - web_data:/bitnami
      - ./entry1.sh:/post-init.d/entry1.sh
    depends_on:
      - db
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=bn_user
      # - MARIADB_PASSWORD=bitnami_db
      - storage.default-namespace
      - PHP_MEMORY_LIMIT=256M


volumes:
  db_data:
    driver: local
  web_data:
    driver: local
