version: '3.7'


services:

  # # nopass
  # redis1:
  #   image: bitnami/redis
  #   ports:
  #     - 6001:6379
  #   volumes:
  #     - db-cert:/opt/bitnami/redis/certs
  #     - db_data:/bitnami/redis/data
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  # # password
  # redis2:
  #   image: bitnami/redis
  #   ports:
  #     - 6002:6379
  #   volumes:
  #     - db-cert:/opt/bitnami/redis/certs
  #     - db_data:/bitnami/redis/data
  #   environment:
  #     - REDIS_PASSWORD=password
  #     - DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  # cert
  redis3:
    image: bitnami/redis:6.0
    ports:
      - 6003:6379
    # sysctls:
    #   vm.overcommit_memory: 1
    #   vm.overcommit_ratio: 50
    volumes:
      # - db-cert:/opt/bitnami/redis/certs
      - ./certs:/opt/bitnami/redis/certs
      # 추가는 불가
      # - ./config/redis.conf:/etc/sysctl.d/redis.conf
      - db_data:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=password
      # - DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      # # tls
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt
      - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key
      - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/rootCA.crt
      # - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/cm_cert.pem
      # - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/cm_key.pem
      # - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/cm_cert.p12
# https://github.com/StackExchange/StackExchange.Redis/issues/772
# https://github.com/StackExchange/StackExchange.Redis/issues/766#issuecomment-357506555

volumes:
  db-cert:
    driver: local
  db_data:
    driver: local
